import json
import re
from datetime import datetime, timedelta
import pytz
import csv

from rca.baseline.rag_tool_multicandidate_agent.executor import execute_act
from rca.api_router import get_chat_completion
from ..rag_agent.rag_retriever_new_data import PostmortemRAGRetriever
from ..rag_agent.controller import summarize_observation_for_rag


# ==================== System & Format Templates (unchanged) ====================
system = """You are the Administrator of a DevOps Assistant system for failure diagnosis. To solve each given issue, you can iteratively apply pre-designed Multivariate Time Series Anomaly Detection tools—specifically tailored for traces, metrics, and logs—to analyze whether multiple attributes of specified microservice entities exhibit anomalies within a given time window. By examining the resulting multi-entity, multi-attribute anomaly timeline data generated by these tools, you should approximate the answer step-by-step.

There is some domain knowledge for you:

{background}

{agent}

The issue you are going to solve is:

{objective}

Solve the issue step-by-step. Let's begin."""

summary = """Now, you have decided to finish your reasoning process. You should now provide the final answer to the issue. The candidates of possible root cause components and reasons are provided to you. The root cause components and reasons must be selected from the provided candidates.

{cand}

Recall the issue is: {objective}

Please first confirm the issue description time scope. For example:
- If the description says "between 14:30 and 15:00 on March 4, 2021", the time scope is from 1614839400 to 1614841200 (UTC+8).
Secondly, review your reasoning to infer the exact root cause within that time scope.
Thirdly, output your final answer using the following JSON format:

```json
{{
    "1": {{
        "Suspicious score": 0.95,
        "root cause occurrence datetime": "2021-03-04 14:32:00",
        "root cause component": "user-service",
        "root cause reason": "high CPU usage"
    }}
}}
```
"""

backgroud_Bank="""
# Call Chain Description (Technical Narrative)

The observed trace reveals the following end-to-end service invocation pattern:

1. An external request enters the system through the **IG** (Integration Gateway).  
2. The IG forwards the request to a **Tomcat** application server for business logic processing.  
3. During execution, Tomcat invokes a downstream **MG** (Microservice Gateway) to access core microservices.  
4. The MG, in turn, interacts with services running inside **Docker** containers—either by calling containerized workloads or delegating tasks to them.  
5. Additionally, there is a reverse interaction where **Docker-hosted components initiate calls back to the MG**, suggesting a bidirectional integration pattern (e.g., event-driven callbacks or sidecar coordination).

## Complete Core Dependency Chain (Including Invisible/Embedded Components)
**Client → apache (Load Balancing) → IG → Tomcat (⇆ Redis) → MG (⇆ Redis) ⇄ Dockerized Services (→ Mysql)**

### Component-by-Component Explanation and Breakdown
1. **Client → apache**
apache (apache01/apache02) serves as the **invisible entry point** at the foremost tier of the entire call chain. Although it is a mandatory pass-through for all external client requests, it is not captured in distributed trace data. This is because the trace collection probes are not deployed on the apache load balancers, which only undertake basic request forwarding and traffic distribution without handling business logic, thus failing to generate traceable spans.

2. **apache → IG**
The IG layer (IG01/IG02, interface gateway services) acts as the **first traceable root node** in the distributed tracing system. It receives requests forwarded by the apache load balancers and executes core gateway functions such as request authentication, protocol conversion, and service routing before relaying the requests to the downstream Tomcat business layer. All requests entering the backend microservice cluster are first recorded as trace spans at the IG tier.

3. **IG → Tomcat**
The Tomcat tier (Tomcat01, Tomcat02, Tomcat03, or Tomcat04) is the **core business logic layer** of the banking system, responsible for processing key business workflows like transaction verification and user information management. The notation `(⇆ Redis)` indicates that Tomcat services have bidirectional embedded dependencies on Redis (Redis01/Redis02). Specifically, Tomcat instances query Redis for cached data (e.g., user sessions, transaction configurations) during business processing to improve response efficiency. However, this Redis access is treated as an **internal resource call** rather than an inter-service RPC invocation, so it does not generate independent trace spans and is only reflected in the latency metrics of Tomcat’s trace spans.

4. **Tomcat → MG**
The MG tier (MG01/MG02, microservice governance middleware) provides service governance capabilities such as service registration and discovery, circuit breaking, and distributed transaction coordination for the system. Similar to the Tomcat tier, the `(⇆ Redis)` annotation here denotes that MG components invoke Redis to retrieve configuration information or distributed lock resources during request routing and permission verification. This Redis dependency is also an internal resource access and is not captured as a separate trace span in the distributed tracing system.

5. **MG ⇄ Dockerized Services**
The bidirectional arrow (`⇄`) represents the **mutual interaction** between the MG middleware and containerized business services (e.g., dockerB1): the MG tier forwards standardized business requests to containerized services, and the containerized services return processing results to the MG tier. The suffix `(→ Mysql)` indicates that containerized services ultimately call the Mysql database (Mysql01/Mysql02) for persistent data storage (e.g., transaction ledger recording, account data writing). If trace probes are not deployed on the Mysql client of containerized services, this database access will not generate independent trace spans and will only be counted as part of the latency of containerized service spans.

- IG might be IG01 or IG02
- MG might be MG01 or MG02
- apache might be apache01 or apache02
- Tomcat might be Tomcat01, Tomcat02, Tomcat03, or Tomcat04
- docker might be dockerA1, dockerA2, dockerB1, or dockerB2
- Mysql might be Mysql01 or Mysql02

Notably, the mutual dependency between **MG** and **Docker** implies that the MG not only orchestrates calls to containerized services but may also expose endpoints consumed by those same containers—common in modern cloud-native designs involving control planes, agent-based monitoring, or asynchronous task processing.

Apply these RCA Decision Rules:
- **Sustained Anomaly Priority**: Prefer entities with ≥3 anomalies on the same metric within 5 minutes.
- **Earliest Among Sustained**: If multiple sustained anomalies exist, pick the one starting earliest.
- **Log as Trigger Only**: Treat log anomalies as high-confidence only if they precede sustained metric anomalies by ≤2 minutes.
- **Upstream over Downstream**: Favor components that are called by others (per trace data) and fail first.
- **Ignore Isolated Events**: Single-point anomalies without corroboration are likely symptoms.

Only include fields explicitly asked in the issue. All components/reasons must come from the candidate list. Be decisive.
"""

backgroud_Telecom=""""
"""

backgroud_Market=""""
"""

# ==================== Helper: Extract time from text ====================
def extract_time_from_context(context: str):
    """Extract first HH:MM or HH:MM:SS from context string."""
    time_match = re.search(r'\b(\d{1,2}:\d{2}:\d{2}|\d{1,2}:\d{2})\b', context)
    if time_match:
        time_str = time_match.group(1)
        parts = time_str.split(':')
        if len(parts) == 2:
            time_str += ":00"
        try:
            datetime.strptime(time_str, "%H:%M:%S")
            return time_str
        except ValueError:
            pass
    return None


def control_loop(dataset: str, objective: str, plan: str, ap, bp, logger, max_step=15, max_turn=3, rag_k=5) -> tuple:
    # Step 0: Parse time info once for reference
    try:
        time_info = ""
        backgroud = ""
        if dataset == "Telecom":
            instruction, time_info = Telecom_parse_rca_task(objective)
            backgroud = backgroud_Telecom
        elif dataset == "Bank":
            instruction, time_info = parse_rca_task(objective)
            backgroud = backgroud_Bank
        elif dataset == "Market/cloudbed-1": 
            instruction, time_info = Market_parse_rca_task(objective, "cloudbed-1")
            backgroud = backgroud_Market
        elif dataset == "Market/cloudbed-2":
            instruction, time_info = Market_parse_rca_task(objective, "cloudbed-2")
            backgroud = backgroud_Market
        
        logger.info(f"[Step 0] time_info:\n{time_info}")
    except Exception as e:
        logger.error(f"Time parsing failed: {e}")
        return "Time parsing failed. No root cause found.", [], []

    # Build initial system prompt
    system_prompt = system.format(
        objective=objective,
        agent=ap.rules,
        background=bp.schema
    )
    history = []
    trajectory = []
    observation = f"Note: when you use tools, please strictly follow the format: {time_info}. Meanwhile, the time zone is UTC+8. The instruction must contain start_ts and end_ts from the time_info. Let's begin."

    # Run iterative steps to get raw_observation (typically just one step needed)
    raw_observation = ""
    for step in range(max_step):
        try:
            
            logger.info(f"controller instruction:\n{instruction}")

            result, exec_status, new_history = execute_act(
                dataset, instruction, history, logger
            )
            if exec_status:
                raw_observation = str(result)
                history = new_history
                trajectory.append({
                    'result': f"Out[{step+1}]:\n```\n{result}\n```"
                })
            else:
                raw_observation = "Executor failed."

            # Break after first successful tool call (assumes multi-cluster output)
            break

        except Exception as e:
            logger.error(f"Error at step {step + 1}: {e}")
            raw_observation = f"Error: {str(e)}"
            break

    # ==================== PARSE CLUSTERS ====================
    try:
        
        raw_clean = raw_observation.strip()
        if raw_clean.startswith("```"):
            # 提取 ```json 和 ``` 之间的内容
            match = re.search(r"```(?:json)?\s*({.*})\s*```", raw_clean, re.DOTALL)
            if match:
                raw_clean = match.group(1)
            else:
                # 如果格式不标准，尝试去掉首尾的 ```
                raw_clean = re.sub(r"^```.*?\n", "", raw_clean, count=1)
                raw_clean = re.sub(r"\n```$", "", raw_clean)
        
        observation_dict = json.loads(raw_clean)
        clusters = list(observation_dict.items())
        logger.info(f"Parsed {len(clusters)} clusters from tool output.")
    except Exception as e:
        logger.error(f"Failed to parse clusters: {e}")
        clusters = [("Fallback", raw_clean)]

    # ==================== GET BASE DATE FROM OBJECTIVE ====================
    tz = pytz.timezone('Asia/Shanghai')
    try:
        date_match = re.search(r'([A-Za-z]+\s+\d{1,2},\s+\d{4})', objective)
        if date_match:
            base_date_str = date_match.group(1)
            base_date = datetime.strptime(base_date_str, "%B %d, %Y").date()
        else:
            base_date = datetime.fromtimestamp(time_info["start_ts"], tz=tz).date()
    except Exception as e:
        logger.warning(f"Failed to extract base date from objective: {e}")
        base_date = datetime.fromtimestamp(time_info["start_ts"], tz=tz).date()

    # ==================== PER-CLUSTER RAG + LOCAL RCA ====================
    cluster_rca_candidates = []

    for cluster_id, cluster_desc in clusters:
        logger.info(f"controller Processing {cluster_id}: {cluster_desc}")
        logger.info(f"RAG rag_k: {rag_k}")

        # --- RAG ---
        rag_context = ""
        
        # RAG core logic start
        try:
            refined_query = summarize_observation_for_rag(cluster_desc, logger)
            logger.info(f"controller summarize {cluster_id} result: {refined_query}")
            retriever = PostmortemRAGRetriever()
            rag_results = retriever.retrieve(query=refined_query, k=rag_k, score_threshold=0.7)
            logger.info(f"controller RAG {cluster_id} result: {rag_results}")
            if rag_results:
                snippets = []
                for i, res in enumerate(rag_results, 1):
                    meta = res['metadata']
                    comp = meta.get('component', 'N/A')
                    metrics = ", ".join(meta.get("metrics", [])) or "N/A"
                    snippet = (
                        f"[Past Incident {i}] (Score: {res['score']:.3f})\n"
                        f"Component: {comp} | Metrics: {metrics}\n"
                        f"Summary: {res['content']}"
                    )
                    snippets.append(snippet)
                rag_context = "\n".join(snippets)
        except Exception as e:
            logger.error(f"RAG failed for {cluster_id}: {e}")
        
        # RAG core logic end

        # --- Local RCA Prompt ---
        local_rca_prompt = f"""You are analyzing a specific anomaly cluster during the time window of the original issue.
{system_prompt}

Original Issue Time Window: {time_info['date_online']} from {time_info['output_suffix'][:4]} to {time_info['output_suffix'][5:]} (UTC+8)

Candidate Root Cause Components (MUST choose from this list):
{bp.cand}

Anomaly Cluster Description:
{cluster_desc}

Relevant Historical Incidents (if any):
{rag_context if rag_context else 'None'}

Backgroud:
{backgroud}

Based on this information, identify the MOST LIKELY root cause component and reason from the candidate list.
Follow these rules:
- The root cause must be a single component from the candidate list.
- The reason must be directly supported by the anomaly description.
- Assign a suspicious score between 0.0 and 1.0 (higher = more confident).

Respond ONLY with a JSON object in this exact format:
{{
    "component": "service-name",
    "reason": "brief reason",
    "score": 0.92
}}"""

        try:
            messages = [
                {'role': 'system', 'content': 'You are a precise root cause analyst.'},
                {'role': 'user', 'content': local_rca_prompt}
            ]
            logger.info(f"controller Local RCA for {cluster_id} request: {messages}")
            local_response = get_chat_completion(logger, messages = messages)
            logger.info(f"controller Local RCA for {cluster_id} response: {local_response}")

            json_match = re.search(r"\{.*\}", local_response, re.DOTALL)
            if json_match:
                candidate = json.loads(json_match.group(0))
                
                # ==================== DEFENSIVE PARSING & VALIDATION ====================
                raw_comp = candidate.get("component")
                raw_reason = candidate.get("reason")
                raw_score = candidate.get("score")

                # Sanitize component
                if not isinstance(raw_comp, str):
                    comp = ""
                else:
                    comp = raw_comp.strip()

                # Sanitize reason
                if not isinstance(raw_reason, str):
                    reason = "N/A"
                else:
                    reason = raw_reason.strip()

                # Sanitize score
                try:
                    score = float(raw_score) if raw_score is not None else 0.0
                except (ValueError, TypeError):
                    score = 0.0

                logger.info(f"[DEBUG] Parsed LLM output -> comp: '{comp}', reason: '{reason}', score: {score}")

                # --- Robust parsing of candidate components from bp.cand ---
                cand_lines = [line.strip() for line in bp.cand.strip().split('\n')]
                components_section = False
                cand_list = []

                for line in cand_lines:
                    if line.startswith("## POSSIBLE ROOT CAUSE COMPONENTS:"):
                        components_section = True
                        continue
                    if components_section and line.startswith("## "):
                        break
                    if components_section and line.startswith("- "):
                        comp_name = line[2:].strip()
                        if comp_name:
                            cand_list.append(comp_name)

                logger.info(f"[DEBUG] Cleaned candidate component list: {cand_list}")

                # --- Validation ---
                if not comp:
                    logger.warning(f"Empty component name for {cluster_id}")
                elif score <= 0.0:
                    logger.warning(f"Non-positive score ({score}) for {cluster_id}")
                elif comp not in cand_list:
                    logger.warning(f"Component '{comp}' not in candidate list. Candidates: {cand_list}")
                else:
                    cluster_rca_candidates.append({
                        "cluster_id": cluster_id,
                        "component": comp,
                        "reason": reason,
                        "score": score,
                        "context": cluster_desc
                    })
            else:
                logger.warning(f"No JSON in local RCA response for {cluster_id}")
        except Exception as e:
            logger.error(f"Local RCA failed for {cluster_id}: {e}")

    # --- DEBUG: Print all valid cluster RCA candidates ---
    logger.info(">>> Final cluster_rca_candidates (raw list):")
    for idx, cand in enumerate(cluster_rca_candidates, 1):
        logger.info(
            f"  Candidate {idx}:\n"
            f"    cluster_id: {cand.get('cluster_id', 'N/A')}\n"
            f"    component: {cand.get('component', 'N/A')}\n"
            f"    reason: {cand.get('reason', 'N/A')}\n"
            f"    score: {cand.get('score', 'N/A')}\n"
            f"    context_snippet: {cand.get('context', '')}..."
        )

    # ==================== BUILD FINAL ANSWER WITH GENERIC TIME ====================
    final_answer_dict = {}
    for i, cand in enumerate(sorted(cluster_rca_candidates, key=lambda x: x["score"], reverse=True)[:10], 1):
        extracted_time = extract_time_from_context(cand["context"])
        
        if extracted_time:
            occurrence_time = f"{base_date.strftime('%Y-%m-%d')} {extracted_time}"
        else:
            start_dt = datetime.fromtimestamp(time_info["start_ts"], tz=tz)
            end_dt = datetime.fromtimestamp(time_info["end_ts"], tz=tz)
            mid_dt = start_dt + (end_dt - start_dt) / 2
            occurrence_time = mid_dt.strftime("%Y-%m-%d %H:%M:%S")

        final_answer_dict[str(i)] = {
            "Suspicious score": round(cand["score"], 4),
            "root cause occurrence datetime": occurrence_time,
            "root cause component": cand["component"],
            "root cause reason": cand["reason"]
        }

    final_answer = json.dumps(final_answer_dict, indent=2, ensure_ascii=False)

    logger.info("Final RCA Candidates (Top@10):")
    for idx, c in enumerate(cluster_rca_candidates[:10], 1):
        logger.info(f"  {idx}. [{c['score']:.3f}] {c['component']} - {c['reason']} ({c['cluster_id']})")

    return final_answer, trajectory



def parse_rca_task(task_description: str):
    tz = pytz.timezone('Asia/Shanghai')
    
    # --- Extract first date string ---
    date_match = re.search(r'([A-Za-z]+\s+\d{1,2},\s+\d{4})', task_description)
    if not date_match:
        raise ValueError("Date (e.g., 'March 4, 2021') not found in task description.")
    start_date_str = date_match.group(1)

    # --- Cross-day time pattern (FIXED) ---
    cross_pattern = r'(?:from|between)\s+(\d{1,2}:\d{2})\s+(?:to|and)\s+([A-Za-z]+\s+\d{1,2},\s+\d{4})[,.\s]*(?:at\s+)?(\d{1,2}:\d{2})'
    cross_match = re.search(cross_pattern, task_description, re.IGNORECASE)

    # --- Same-day time pattern ---
    same_day_pattern = r'(?:from|between|during the time range of|within the time range of|between the time range of|in the time range of)?\s*(\d{1,2}:\d{2})\s+(?:to|and)\s+(\d{1,2}:\d{2})'
    same_day_match = re.search(same_day_pattern, task_description, re.IGNORECASE)

    if cross_match:
        start_time_str = cross_match.group(1)
        end_date_str = cross_match.group(2)
        end_time_str = cross_match.group(3)
        start_dt = datetime.strptime(f"{start_date_str} {start_time_str}", "%B %d, %Y %H:%M")
        end_dt = datetime.strptime(f"{end_date_str} {end_time_str}", "%B %d, %Y %H:%M")
    elif same_day_match:
        start_time_str, end_time_str = same_day_match.groups()
        start_dt = datetime.strptime(f"{start_date_str} {start_time_str}", "%B %d, %Y %H:%M")
        end_dt = datetime.strptime(f"{start_date_str} {end_time_str}", "%B %d, %Y %H:%M")
    else:
        raise ValueError("Time range not found in task description.")

    start_dt = tz.localize(start_dt)
    end_dt = tz.localize(end_dt)

    start_ts = int(start_dt.timestamp())
    end_ts = int(end_dt.timestamp())
    date_online = start_dt.strftime("%Y_%m_%d")
    output_suffix = f"{start_dt.strftime('%H%M')}_{end_dt.strftime('%H%M')}"

    date_offline = "2021_03_05"
    output_folder_name = "1204"

    return_json = {
        "pipeline_type": "all",
        "date_offline": date_offline,
        "date_online": date_online,
        "start_ts": start_ts,
        "end_ts": end_ts,
        "method": "TranAD",
        "output_folder_name": output_folder_name,
        "output_suffix": output_suffix
    }
    
    import json
    text = json.dumps(return_json)
    return text, return_json
    
def Telecom_parse_rca_task(task_description: str):
    tz = pytz.timezone('Asia/Shanghai')
    
    # --- Extract first date string ---
    date_match = re.search(r'([A-Za-z]+\s+\d{1,2},\s+\d{4})', task_description)
    if not date_match:
        raise ValueError("Date (e.g., 'March 4, 2021') not found in task description.")
    start_date_str = date_match.group(1)

    # --- Cross-day time pattern (FIXED) ---
    cross_pattern = r'(?:from|between)\s+(\d{1,2}:\d{2})\s+(?:to|and)\s+([A-Za-z]+\s+\d{1,2},\s+\d{4})[,.\s]*(?:at\s+)?(\d{1,2}:\d{2})'
    cross_match = re.search(cross_pattern, task_description, re.IGNORECASE)

    # --- Same-day time pattern ---
    same_day_pattern = r'(?:from|between|during the time range of|within the time range of|between the time range of|in the time range of)?\s*(\d{1,2}:\d{2})\s+(?:to|and)\s+(\d{1,2}:\d{2})'
    same_day_match = re.search(same_day_pattern, task_description, re.IGNORECASE)

    if cross_match:
        start_time_str = cross_match.group(1)
        end_date_str = cross_match.group(2)
        end_time_str = cross_match.group(3)
        start_dt = datetime.strptime(f"{start_date_str} {start_time_str}", "%B %d, %Y %H:%M")
        end_dt = datetime.strptime(f"{end_date_str} {end_time_str}", "%B %d, %Y %H:%M")
    elif same_day_match:
        start_time_str, end_time_str = same_day_match.groups()
        start_dt = datetime.strptime(f"{start_date_str} {start_time_str}", "%B %d, %Y %H:%M")
        end_dt = datetime.strptime(f"{start_date_str} {end_time_str}", "%B %d, %Y %H:%M")
    else:
        raise ValueError("Time range not found in task description.")

    start_dt = tz.localize(start_dt)
    end_dt = tz.localize(end_dt)

    start_ts = int(start_dt.timestamp())
    end_ts = int(end_dt.timestamp())
    date_online = start_dt.strftime("%Y_%m_%d")
    output_suffix = f"{start_dt.strftime('%H%M')}_{end_dt.strftime('%H%M')}"

    date_offline = "2020_04_20"
    output_folder_name = "1216"
    
    return_json = {
        "pipeline_type": "all",
        "date_offline": date_offline,
        "date_online": date_online,
        "start_ts": start_ts,
        "end_ts": end_ts,
        "method": "TranAD",
        "output_folder_name": output_folder_name,
        "output_suffix": output_suffix
    }
    
    import json
    text = json.dumps(return_json)
    return text, return_json
    
import re
import pytz
from datetime import datetime
import pandas as pd
import os

def Market_parse_rca_task(task_description: str, cloudbed: str):
    tz = pytz.timezone('Asia/Shanghai')
    
    # --- Extract first date string ---
    date_match = re.search(r'([A-Za-z]+\s+\d{1,2},\s+\d{4})', task_description)
    if not date_match:
        raise ValueError("Date (e.g., 'March 4, 2021') not found in task description.")
    start_date_str = date_match.group(1)

    # --- Cross-day time pattern ---
    cross_pattern = r'(?:from|between)\s+(\d{1,2}:\d{2})\s+(?:to|and)\s+([A-Za-z]+\s+\d{1,2},\s+\d{4})[,.\s]*(?:at\s+)?(\d{1,2}:\d{2})'
    cross_match = re.search(cross_pattern, task_description, re.IGNORECASE)

    # --- Same-day time pattern ---
    same_day_pattern = r'(?:from|between|during the time range of|within the time range of|between the time range of|in the time range of)?\s*(\d{1,2}:\d{2})\s+(?:to|and)\s+(\d{1,2}:\d{2})'
    same_day_match = re.search(same_day_pattern, task_description, re.IGNORECASE)

    if cross_match:
        start_time_str = cross_match.group(1)
        end_date_str = cross_match.group(2)
        end_time_str = cross_match.group(3)
        start_dt = datetime.strptime(f"{start_date_str} {start_time_str}", "%B %d, %Y %H:%M")
        end_dt = datetime.strptime(f"{end_date_str} {end_time_str}", "%B %d, %Y %H:%M")
    elif same_day_match:
        start_time_str, end_time_str = same_day_match.groups()
        start_dt = datetime.strptime(f"{start_date_str} {start_time_str}", "%B %d, %Y %H:%M")
        end_dt = datetime.strptime(f"{start_date_str} {end_time_str}", "%B %d, %Y %H:%M")
    else:
        raise ValueError("Time range not found in task description.")

    start_dt = tz.localize(start_dt)
    end_dt = tz.localize(end_dt)

    date_online_start_ts = int(start_dt.timestamp())
    date_online_end_ts = int(end_dt.timestamp())
    date_online = start_dt.strftime("%Y_%m_%d")
    output_suffix = f"{start_dt.strftime('%H%M')}_{end_dt.strftime('%H%M')}"

    # --- Load offline normal window from CSV based on online timestamps and cloudbed ---
    csv_path = f"/root/shared-nvme/work/timeSeries/OmniTransfer_new/Market_utils/{cloudbed}_record_with_normal_intervals_new_new.csv"
    if not os.path.exists(csv_path):
        raise FileNotFoundError(f"CSV file for {cloudbed} not found at {csv_path}")

    df = pd.read_csv(csv_path)

    # Convert relevant columns to integers if not already
    df['fault_window_start_timestamp'] = df['fault_window_start_timestamp'].astype(int)
    df['fault_window_end_timestamp'] = df['fault_window_end_timestamp'].astype(int)
    df['normal_window_start_timestamp'] = df['normal_window_start_timestamp'].astype(int)
    df['normal_window_end_timestamp'] = df['normal_window_end_timestamp'].astype(int)

    # Find a row where the online interval [start_ts, end_ts] is within [fault_window_start, fault_window_end]
    matched_row = None
    for _, row in df.iterrows():
        if (row['fault_window_start_timestamp'] <= date_online_start_ts and
            date_online_end_ts <= row['fault_window_end_timestamp']):
            matched_row = row
            break

    if matched_row is None:
        raise ValueError(
            f"No matching fault window found in {cloudbed} for online interval "
            f"[{date_online_start_ts}, {date_online_end_ts}]"
        )

    date_offline_start_ts = int(matched_row['normal_window_start_timestamp'])
    date_offline_end_ts = int(matched_row['normal_window_end_timestamp'])
    date_offline_dt = datetime.fromtimestamp(date_offline_start_ts, tz=tz)
    date_offline = date_offline_dt.strftime("%Y_%m_%d")
    
    # ⚠️ ONLY HERE: adjust date_online_start_ts by subtracting 30 minutes (1800 seconds)
    adjusted_date_online_start_ts = date_online_start_ts - 1800
    
    return_json = {
        "cloudbed": cloudbed,
        "pipeline_type": "all",
        "date_offline": date_offline,
        "date_offline_start_ts": date_offline_start_ts,
        "date_offline_end_ts": date_offline_end_ts,
        "date_online": date_online,
        "date_online_start_ts": adjusted_date_online_start_ts,
        "date_online_end_ts": date_online_end_ts,
        "start_ts": adjusted_date_online_start_ts,
        "end_ts": date_online_end_ts,
        "method": "TranAD",
        "data_dir": "data2",
        "output_folder_name": "1215",
        "output_suffix": output_suffix
    }
    
    import json
    text = json.dumps(return_json)
    return text, return_json

# -----------------------------
# Main test loop
# run script
# cd /root/shared-nvme/work/agent/OpenRCA
# python -m rca.baseline.rag_tool_multicandidate_agent.controller
# -----------------------------
if __name__ == '__main__':
    csv_path = "/root/shared-nvme/work/agent/OpenRCA/dataset/Telecom/query.csv"
    failed_cases = []

    with open(csv_path, 'r', encoding='utf-8') as f:
        reader = csv.DictReader(f)
        for i, row in enumerate(reader, start=1):
            task_index = row['task_index']
            instruction = row['instruction']
            try:
                result = Telecom_parse_rca_task(instruction)
                # result = Market_parse_rca_task(instruction, "cloudbed-2")                
                # print(f"[OK] Line {i} ({task_index}): Parsed -> {result['date_online']} {result['output_suffix']}")
                print(f"[OK] Line {i} ({task_index}): Parsed -> {result}")
            except Exception as e:
                failed_cases.append((i, task_index, instruction, str(e)))
                print(f"[FAIL] Line {i} ({task_index}): {e}")
    
    print("\n" + "="*60)
    if failed_cases:
        print(f"❌ {len(failed_cases)} cases failed:")
        for line_num, task_id, instr, err in failed_cases:
            print(f"\nLine {line_num} | Task: {task_id}")
            print(f"Instruction: {instr}")
            print(f"Error: {err}")
    else:
        print("✅ All instructions parsed successfully!")