import json
import re
from IPython.terminal.embed import InteractiveShellEmbed

from rca.baseline.rag_tool_agent.executor import execute_act

from rca.api_router import get_chat_completion

from ..rag_agent.rag_retriever_new_data import PostmortemRAGRetriever
from ..rag_agent.controller import summarize_observation_for_rag

system = """You are the Administrator of a DevOps Assistant system for failure diagnosis. To solve each given issue, You can iteratively apply pre-designed Multivariate Time Series Anomaly Detection tools—specifically tailored for traces, metrics, and logs—to analyze whether multiple attributes of specified microservice entities exhibit anomalies within a given time window. By examining the resulting multi-entity, multi-attribute anomaly timeline data generated by these tools, you should approximate the answer step-by-step.

There is some domain knowledge for you:

{background}

{agent}

The issue you are going to solve is:

{objective}

Solve the issue step-by-step. In each step, your response should follow the JSON format below:

{format}

Let's begin."""

format = """{
    "analysis": (Your analysis of the code execution result from Executor in the last step, with detailed reasoning of 'what have been done' and 'what can be derived'. Respond 'None' if it is the first step.),
    "completed": ("True" if you believe the issue is resolved, and an answer can be derived in the 'instruction' field. Otherwise "False"),
    "instruction": (Your instruction for the Executor to perform via code execution in the next step. Do not involve complex multi-step instruction. Keep your instruction atomic, with clear request of 'what to do' and 'how to do'. Respond a summary by yourself if you believe the issue is resolved. Respond a summary by yourself if you believe the issue is resolved. Respond a summary by yourself if you believe the issue is resolved.)
}
(DO NOT contain "```json" and "```" tags. DO contain the JSON object with the brackets "{}" only. Use '\\n' instead of an actual newline character to ensure JSON compatibility when you want to insert a line break within a string.)"""

summary = """Now, you have decided to finish your reasoning process. You should now provide the final answer to the issue. The candidates of possible root cause components and reasons are provided to you. The root cause components and reasons must be selected from the provided candidates.

{cand}

Recall the issue is: {objective}

Please first confirm the issue description time scope, e.g., if the description is "the specified time range of March 8, 2021, from 19:00 to 19:30", then time scope is from 1615201200 (2021/03/08 19:00:00 UTC+8) to 1615203000 (2021/03/08 19:30:00 UTC+8). Secondly, please review your previous reasoning process to infer an exact answer of the issue. Thirdly, summarize your final answer of the root causes using the following JSON format at the end of your response:

```json
{{
    "1": {{
        "root cause occurrence datetime": (if asked by the issue, format: '%Y-%m-%d %H:%M:%S', otherwise ommited),
        "root cause component": (if asked by the issue, one selected from the possible root cause component list, otherwise ommited),
        "root cause reason": (if asked by the issue, one selected from the possible root cause reason list, otherwise ommited),
    }}, (mandatory)
    "2": {{
        "root cause occurrence datetime": (if asked by the issue, format: '%Y-%m-%d %H:%M:%S', otherwise ommited),
        "root cause component": (if asked by the issue, one selected from the possible root cause component list, otherwise ommited),
        "root cause reason": (if asked by the issue, one selected from the possible root cause reason list, otherwise ommited),
    }}, (only if the failure number is "unknown" or "more than one" in the issue)
    ... (only if the failure number is "unknown" or "more than one" in the issue)
}}
```
(Please use "```json" and "```" tags to wrap the JSON object. You only need to provide the elements asked by the issue, and ommited the other fields in the JSON.)
Note that all the root cause components and reasons must be selected from the provided candidates. Do not reply 'unknown' or 'null' or 'not found' in the JSON. Do not be too conservative in selecting the root cause components and reasons. Be decisive to infer a possible answer based on your current observation."""

def control_loop(objective:str, plan:str, ap, bp, logger, max_step = 15, max_turn = 3) -> str:
   
    prompt = [
            {'role': 'system', 'content': system.format(objective=objective,
                                                        format=format,
                                                        agent=ap.rules, 
                                                        background=bp.schema)},
            {'role': 'user', 'content': "Let's begin."}
        ]

    history = []
    trajectory = []
    observation = "Let's begin."
    status = False
    kernel = InteractiveShellEmbed()
    init_code = "import pandas as pd\n"+ \
            "pd.set_option('display.width', 427)\n"+ \
            "pd.set_option('display.max_columns', 10)\n"
    kernel.run_cell(init_code)

    for step in range(max_step):
        
        note = [{'role': 'user', 'content': f"Continue your reasoning process for the target issue:\n\n{objective}\n\nFollow the rules during issue solving:\n\n{ap.rules}.\n\nResponse format:\n\n{format}"}]
        attempt_actor = []
        try:
            response_raw = get_chat_completion(
                messages=prompt + note,
            )
            if "```json" in response_raw:
                response_raw = re.search(r"```json\n(.*)\n```", response_raw, re.S).group(1).strip()
            logger.debug(f"Raw Response:\n{response_raw}")
            if '"analysis":' not in response_raw or '"instruction":' not in response_raw or '"completed":' not in response_raw:
                logger.warning("Invalid response format. Please provide a valid JSON response.")
                prompt.append({'role': 'assistant', 'content': response_raw})
                prompt.append({'role': 'user', 'content': "Please provide your analysis in requested JSON format."})
                continue
            response = json.loads(response_raw)
            analysis = response['analysis']
            instruction = response['instruction']
            completed = response['completed']
            logger.info('-'*80 + '\n' + f"### Step[{step+1}]\nAnalysis: {analysis}\nInstruction: {instruction}" + '\n' + '-'*80)

            if completed == "True":
                kernel.reset()
                prompt.append({'role': 'assistant', 'content': response_raw})
                prompt.append({'role': 'user', 'content': summary.format(objective=objective,
                                                                                cand=bp.cand)})
                answer = get_chat_completion(
                    messages=prompt,
                )
                logger.debug(f"Raw Final Answer:\n{answer}")
                prompt.append({'role': 'assistant', 'content': answer})
                if "```json" in answer:
                    answer = re.search(r"```json\n(.*)\n```", answer, re.S).group(1).strip()
                return answer, trajectory, prompt

            code, result, status, new_history = execute_act(instruction, bp.schema, history, attempt_actor, kernel, logger, objective)
            if not status:
                logger.warn(f'Self-Correction failed.')
                observation = "The Executor failed to execute the instruction. Please provide a new instruction."
            else:
                observation = f"{result}"
            # history = new_history
            # trajectory.append({'code': f"# In[{step+1}]:\n\n{code}", 'result': f"Out[{step+1}]:\n```\n{result}```"})
            # logger.info('-'*80 + '\n' + f"Step[{step+1}]\n### Observation:\n{result}" + '\n' + '-'*80)
            
            
            # >>>>>>>>>>>>>>>>>> RAG start <<<<<<<<<<<<<<<<<<
            import json
            from typing import Dict, List

            # >>>>>>>>>>>>>>>>>> RAG start <<<<<<<<<<<<<<<<<<
            rag_context = {
                # 初始化空字典，key 为 Cluster 名称，value 为对应 RAG 结果
            }
            try:
                # Step 1: 解析 observation 为 JSON 字典（处理字符串格式的 JSON）
                if isinstance(observation, str):
                    clusters = json.loads(observation)
                elif isinstance(observation, dict):
                    clusters = observation
                else:
                    raise TypeError("Observation must be a JSON string or Python dictionary")

                # Step 2: 为每个 Cluster 执行 RAG 检索，收集结果（含相似度分数）
                cluster_rag_results: List[Dict] = []
                retriever = PostmortemRAGRetriever()  # 单例检索器

                for cluster_name, cluster_content in clusters.items():
                    # 提炼当前 Cluster 内容的 RAG 查询
                    refined_query = summarize_observation_for_rag(cluster_content, logger)
                    
                    # 检索相关历史故障（k=1，可根据需求调整）
                    rag_res = retriever.retrieve(
                        query=refined_query,
                        k=1,
                        score_threshold=0.8
                    )

                    # 构建当前 Cluster 的 RAG 结果
                    if rag_res:
                        res = rag_res[0]  # 取相似度最高的结果
                        meta = res['metadata']
                        comp = meta.get('component', 'N/A')
                        metric = meta.get('metric', 'N/A')
                        source = meta.get('source_file', 'N/A')
                        # 组装单条 RAG 结果字符串
                        rag_content = (
                            f"[Past Incident] (Similarity Score: {res['score']:.4f})\n"
                            f"Component: {comp} | Metric: {metric}\n"
                            f"Source: {source}\n"
                            f"Summary: {res['content'][:400]}..."
                        )
                        # 记录（含相似度分数，用于后续排序）
                        cluster_rag_results.append({
                            "cluster_name": cluster_name,
                            "rag_content": rag_content,
                            "similarity_score": res['score']
                        })
                    else:
                        # 无匹配结果
                        cluster_rag_results.append({
                            "cluster_name": cluster_name,
                            "rag_content": "No sufficiently relevant historical incidents found.",
                            "similarity_score": 0.0  # 无结果时分数设为 0
                        })

                # Step 3: 按 Similarity Score 降序排序（分数越高越靠前）
                cluster_rag_results_sorted = sorted(
                    cluster_rag_results,
                    key=lambda x: x["similarity_score"],
                    reverse=True
                )

                # Step 4: 组装最终的 rag_context（JSON 格式，key 为 Cluster 名称）
                for item in cluster_rag_results_sorted:
                    rag_context[item["cluster_name"]] = item["rag_content"]

                # Step 5: 为每个 Cluster 的 RAG 结果添加统一说明（可选，保持原逻辑）
                note = """\n\nNOTE: The above incidents are from different systems. DO NOT assume the same root cause. 
            Instead, consider: 
            - Does the current symptom match the failure pattern?
            - Is the underlying principle applicable to our architecture?
            - What analogous component might exhibit similar behavior?"""
                
                # 将说明追加到每个 Cluster 的 RAG 结果中
                for cluster_name in rag_context:
                    rag_context[cluster_name] += note

            except json.JSONDecodeError as e:
                logger.error(f"Failed to parse observation JSON: {e}")
                # 异常时返回默认结构
                rag_context = {"error": "Invalid observation JSON format", "detail": str(e)}
            except Exception as e:
                logger.error(f"Advanced RAG failed: {e}")
                rag_context = {"error": "RAG retrieval skipped due to internal error", "detail": str(e)}

            # Step 6: 生成最终的 enhanced_observation（observation + JSON 格式的 rag_context）
            # 若需保持字符串格式，可将 rag_context 转为 JSON 字符串；若需字典格式，直接拼接
            if isinstance(observation, str):
                enhanced_observation = f"{observation}\n\n--- Relevant Past Incidents from Knowledge Base ---\n{json.dumps(rag_context, indent=2, ensure_ascii=False)}"
            else:
                enhanced_observation = {
                    "original_observation": observation,
                    "rag_context": rag_context
                }

            history = new_history
            trajectory.append({'code': f"# In[{step+1}]:\n\n{code}", 'result': f"Out[{step+1}]:\n```\n{cluster_rag_results_sorted}```"})
            logger.info('-'*80 + '\n' + f"Step[{step+1}]\n### RAG Observation:\n{cluster_rag_results_sorted}" + '\n' + '-'*80)
            # >>>>>>>>>>>>>>>>>> RAG end <<<<<<<<<<<<<<<<<<
             
            prompt.append({'role': 'assistant', 'content': response_raw})
            prompt.append({'role': 'user', 'content': enhanced_observation})

        except Exception as e:
            logger.error(e)
            prompt.append({'role': 'assistant', 'content': response_raw})
            prompt.append({'role': 'user', 'content': f"{str(e)}\nPlease provide your analysis in requested JSON format."})
            if 'context_length_exceeded' in str(e):
                logger.warning("Token length exceeds the limit.")
                kernel.reset()
                return "Token length exceeds. No root cause found.", trajectory, prompt

    logger.warning("Max steps reached. Please check the history.")
    kernel.reset()
    final_prompt = {'role': 'user', 'content': summary.format(objective=objective,
                                                                    cand=bp.cand).replace('Now, you have decided to finish your reasoning process. ', 'Now, the maximum steps of your reasoning have been reached. ')}
    if prompt[-1]['role'] == 'user':
        prompt[-1]['content'] = final_prompt['content']
    else:
        prompt.append({'role': 'user', 'content': final_prompt['content']})
    answer = get_chat_completion(
        messages=prompt,
    )
    logger.debug(f"Raw Final Answer:\n{answer}")
    prompt.append({'role': 'assistant', 'content': answer})
    if "```json" in answer:
        answer = re.search(r"```json\n(.*)\n```", answer, re.S).group(1).strip()
    return answer, trajectory, prompt
